name: Deploy Docs to GitHub Pages

on:
  push:
    branches: [main, docs-poc]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Get files
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Generate docs
        run: npx --yes @compodoc/compodoc -p packages/common/tsconfig.json
      - name: Add .nojekyll file
        run: touch ./documentation/.nojekyll
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: documentation
